services:

  postgres:
    container_name: postgres
    image: postgres:11
    volumes:
      - /var/lib/postgresql/data
    networks:
      - dbnet
    restart: always
    ports:
      - "15000:5432"
    environment:
      POSTGRES_DB: "interviewdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  spring:
    container_name: spring-boot
    depends_on:
      - postgres
    build:
      dockerfile: spring.dockerfile
    volumes:
      - /app
    networks:
      - dbnet
    links:
      - postgres
    restart: always
    ports:
      - "15001:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/interviewdb"

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    image: dpage/pgadmin4:8 #major 8.x
    volumes:
      - /var/lib/pgadmin
    networks:
      - dbnet
    links:
      - postgres
    restart: always
    ports:
      - "15002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin

networks:
  dbnet:
    driver: bridge

volumes:
  postgres:
  spring:
  pgadmin: